spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nxtclass
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:nxtclass}
    password: ${DB_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging
logging:
  level:
    com.nxtclass: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN